// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package wang.huaiting.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wang.huaitng.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ralname = 2;</code>
   */
  java.lang.String getRalname();
  /**
   * <code>string ralname = 2;</code>
   */
  com.google.protobuf.ByteString
      getRalnameBytes();
}
