// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package wang.huaiting.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wang.huaitng.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .wang.huaitng.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<wang.huaiting.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .wang.huaitng.proto.StudentResponse studentResponse = 1;</code>
   */
  wang.huaiting.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .wang.huaitng.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .wang.huaitng.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends wang.huaiting.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .wang.huaitng.proto.StudentResponse studentResponse = 1;</code>
   */
  wang.huaiting.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
